import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import type { QRData } from '@/types/qr';

export async function downloadAsPNG(element: HTMLElement, filename: string): Promise<void> {
  try {
    const canvas = await html2canvas(element, {
      backgroundColor: '#ffffff',
      scale: 3,
      logging: false,
      useCORS: true,
    });

    const link = document.createElement('a');
    link.download = `${filename}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  } catch (error) {
    console.error('Error generating PNG:', error);
    throw error;
  }
}

export async function downloadAsPDF(element: HTMLElement, filename: string, data?: QRData): Promise<void> {
  try {
    const canvas = await html2canvas(element, {
      backgroundColor: '#ffffff',
      scale: 3,
      logging: false,
      useCORS: true,
    });

    const imgData = canvas.toDataURL('image/png');

    // Create PDF
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Get PDF dimensions
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();

    // Calculate QR code dimensions (center it)
    const qrSize = 100; // mm
    const x = (pageWidth - qrSize) / 2;
    let y = 40; // mm from top

    // Add title
    pdf.setFontSize(20);
    pdf.setTextColor(234, 88, 12); // Orange color
    pdf.text('QR Code', pageWidth / 2, 20, { align: 'center' });

    // Add QR code image
    pdf.addImage(imgData, 'PNG', x, y, qrSize, qrSize);

    y += qrSize + 20;

    // Add contact info if available
    if (data) {
      pdf.setFontSize(12);
      pdf.setTextColor(0, 0, 0);

      let hasContent = false;

      if (data.firstName || data.lastName) {
        pdf.setFontSize(16);
        pdf.text(`${data.firstName || ''} ${data.lastName || ''}`.trim(), pageWidth / 2, y, { align: 'center' });
        y += 10;
        hasContent = true;
      }

      pdf.setFontSize(10);
      pdf.setTextColor(80, 80, 80);

      if (data.jobTitle) {
        pdf.text(data.jobTitle, pageWidth / 2, y, { align: 'center' });
        y += 8;
        hasContent = true;
      }

      if (data.company) {
        pdf.text(data.company, pageWidth / 2, y, { align: 'center' });
        y += 12;
        hasContent = true;
      }

      y += 5;

      const details: string[] = [];
      if (data.email) details.push(`Email: ${data.email}`);
      if (data.phone) details.push(`Phone: ${data.phone}`);
      if (data.mobile) details.push(`Mobile: ${data.mobile}`);
      if (data.website) details.push(`Website: ${data.website}`);
      if (data.address) details.push(`Address: ${data.address}`);

      if (details.length > 0) {
        pdf.setFontSize(9);
        pdf.setTextColor(60, 60, 60);
        details.forEach((detail) => {
          if (y < pageHeight - 20) {
            pdf.text(detail, pageWidth / 2, y, { align: 'center' });
            y += 6;
            hasContent = true;
          }
        });
      }

      // Add social media
      if (data.social) {
        const socialEntries = Object.entries(data.social).filter(([, url]) => url);
        if (socialEntries.length > 0) {
          y += 8;
          pdf.setFontSize(11);
          pdf.setTextColor(234, 88, 12);
          pdf.text('Social Media', pageWidth / 2, y, { align: 'center' });
          y += 8;

          pdf.setFontSize(8);
          pdf.setTextColor(80, 80, 80);
          socialEntries.forEach(([platform, url]) => {
            if (y < pageHeight - 20) {
              pdf.text(`${platform}: ${url}`, pageWidth / 2, y, { align: 'center' });
              y += 5;
              hasContent = true;
            }
          });
        }
      }

      if (!hasContent) {
        pdf.setFontSize(10);
        pdf.setTextColor(120, 120, 120);
        pdf.text('Scan the QR code to view contact details', pageWidth / 2, y, { align: 'center' });
      }
    }

    // Add footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by Hesham Mohammed Atia QR Code Generator', pageWidth / 2, pageHeight - 10, { align: 'center' });

    pdf.save(`${filename}.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
}
